services:
  - type: web
    name: snackflowmes
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: RENDER_USE_SQLITE
        value: true
      - key: SQLITE_DB_PATH
        value: /tmp/snackflow_render.db
      - key: ConnectionStrings__DefaultConnection
        sync: false