using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SnackFlowMES.Migrations
{
    /// <inheritdoc />
    public partial class DropBomItemUniqueIndex : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Drop the erroneous unique index on ItemId alone.
            // This was auto-generated by EF from the one-to-one relationship config,
            // but it incorrectly prevents creating multiple BOM versions for the same item.
            // The correct uniqueness constraint (ItemId + Version) is kept via IX_Bom_ItemId_Version.
            migrationBuilder.DropIndex(
                name: "IX_BillsOfMaterials_ItemId",
                table: "BillsOfMaterials");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateIndex(
                name: "IX_BillsOfMaterials_ItemId",
                table: "BillsOfMaterials",
                column: "ItemId",
                unique: true);
        }
    }
}
