// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SnackFlowMES.Data;

#nullable disable

namespace SnackFlowMES.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502090338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SnackFlowMES.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SnackFlowMES.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SnackFlowMES.Models.BillOfMaterials", b =>
                {
                    b.Property<int>("BomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BomId"));

                    b.Property<decimal>("BatchOutputQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("BatchOutputUom")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EstLaborHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("EstMachineHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("BomId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("ItemId", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_Bom_ItemId_Version");

                    b.ToTable("BillsOfMaterials");
                });

            modelBuilder.Entity("SnackFlowMES.Models.BomLine", b =>
                {
                    b.Property<int>("BomLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BomLineId"));

                    b.Property<int>("BomId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("QtyPerBatch")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("ScrapPct")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("BomLineId");

                    b.HasIndex("BomId");

                    b.HasIndex("ItemId");

                    b.ToTable("BomLines");
                });

            modelBuilder.Entity("SnackFlowMES.Models.InventoryBalance", b =>
                {
                    b.Property<int>("BalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BalanceId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("QtyOnHand")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("QtyReserved")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("BalanceId");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_InventoryBalance_ItemId");

                    b.ToTable("InventoryBalances");
                });

            modelBuilder.Entity("SnackFlowMES.Models.InventoryLedger", b =>
                {
                    b.Property<int>("LedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LedgerId"));

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PostedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("LedgerId");

                    b.HasIndex("ItemId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("InventoryLedgers");
                });

            modelBuilder.Entity("SnackFlowMES.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("ReorderPoint")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Items_ItemCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("SnackFlowMES.Models.MrpRequirement", b =>
                {
                    b.Property<int>("MrpReqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MrpReqId"));

                    b.Property<decimal>("GrossRequirement")
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool>("IsShortage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("MrpRunId")
                        .HasColumnType("int");

                    b.Property<decimal>("NetRequirement")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("StockOnHand")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("MrpReqId");

                    b.HasIndex("ItemId");

                    b.HasIndex("MrpRunId");

                    b.ToTable("MrpRequirements");
                });

            modelBuilder.Entity("SnackFlowMES.Models.MrpRun", b =>
                {
                    b.Property<int>("MrpRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MrpRunId"));

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RunAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RunByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MrpRunId");

                    b.HasIndex("PlanId");

                    b.ToTable("MrpRuns");
                });

            modelBuilder.Entity("SnackFlowMES.Models.PlanLine", b =>
                {
                    b.Property<int>("PlanLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanLineId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("PlannedQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("ProductionLine")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("PlanLineId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanLines");
                });

            modelBuilder.Entity("SnackFlowMES.Models.ProductionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("LaborHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MachineHours")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("ProducedQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("RecordedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<decimal>("ScrapQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Shift")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ProductionLogs");
                });

            modelBuilder.Entity("SnackFlowMES.Models.ProductionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("PlanDateFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PlanDateTo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PlanId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ProductionPlans");
                });

            modelBuilder.Entity("SnackFlowMES.Models.QcResult", b =>
                {
                    b.Property<int>("QcResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("QcResultId"));

                    b.Property<string>("CheckType")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DefectQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("Disposition")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InspectedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("SampleQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("QcResultId");

                    b.HasIndex("InspectedByUserId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("QcResults");
                });

            modelBuilder.Entity("SnackFlowMES.Models.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ActualQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("PlanLineId")
                        .HasColumnType("int");

                    b.Property<decimal>("PlannedQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("ProductionLine")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("ScheduledEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WoNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("BomId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlanLineId");

                    b.HasIndex("WoNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkOrders_WoNumber");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("SnackFlowMES.Models.WorkOrderCost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CostId"));

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ComputedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(14,4)");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("LaborRatePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MachineCost")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("MachineRatePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaterialCost")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<decimal>("OtherCost")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("CostId");

                    b.HasIndex("WorkOrderId")
                        .IsUnique();

                    b.ToTable("WorkOrderCosts");
                });

            modelBuilder.Entity("SnackFlowMES.Models.WorkOrderMaterial", b =>
                {
                    b.Property<int>("WoMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WoMaterialId"));

                    b.Property<decimal>("ActualQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("PlannedQty")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("UnitCostSnapshot")
                        .HasColumnType("decimal(12,4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("WoMaterialId");

                    b.HasIndex("ItemId");

                    b.HasIndex("WorkOrderId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_WoMaterial_WoId_ItemId");

                    b.ToTable("WorkOrderMaterials");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SnackFlowMES.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SnackFlowMES.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SnackFlowMES.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SnackFlowMES.Models.AuditLog", b =>
                {
                    b.HasOne("SnackFlowMES.Models.ApplicationUser", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SnackFlowMES.Models.BillOfMaterials", b =>
                {
                    b.HasOne("SnackFlowMES.Models.Item", "Item")
                        .WithOne("Bom")
                        .HasForeignKey("SnackFlowMES.Models.BillOfMaterials", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SnackFlowMES.Models.BomLine", b =>
                {
                    b.HasOne("SnackFlowMES.Models.BillOfMaterials", "Bom")
                        .WithMany("BomLines")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.Item", "Item")
                        .WithMany("BomLines")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SnackFlowMES.Models.InventoryBalance", b =>
                {
                    b.HasOne("SnackFlowMES.Models.Item", "Item")
                        .WithOne("InventoryBalance")
                        .HasForeignKey("SnackFlowMES.Models.InventoryBalance", "ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SnackFlowMES.Models.InventoryLedger", b =>
                {
                    b.HasOne("SnackFlowMES.Models.Item", "Item")
                        .WithMany("InventoryLedgers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.WorkOrder", "WorkOrder")
                        .WithMany("InventoryLedgers")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Item");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SnackFlowMES.Models.MrpRequirement", b =>
                {
                    b.HasOne("SnackFlowMES.Models.Item", "Item")
                        .WithMany("MrpRequirements")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.MrpRun", "MrpRun")
                        .WithMany("Requirements")
                        .HasForeignKey("MrpRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("MrpRun");
                });

            modelBuilder.Entity("SnackFlowMES.Models.MrpRun", b =>
                {
                    b.HasOne("SnackFlowMES.Models.ProductionPlan", "Plan")
                        .WithMany("MrpRuns")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SnackFlowMES.Models.PlanLine", b =>
                {
                    b.HasOne("SnackFlowMES.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.ProductionPlan", "Plan")
                        .WithMany("PlanLines")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("SnackFlowMES.Models.ProductionLog", b =>
                {
                    b.HasOne("SnackFlowMES.Models.ApplicationUser", "RecordedBy")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.WorkOrder", "WorkOrder")
                        .WithMany("ProductionLogs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordedBy");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SnackFlowMES.Models.ProductionPlan", b =>
                {
                    b.HasOne("SnackFlowMES.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedPlans")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SnackFlowMES.Models.QcResult", b =>
                {
                    b.HasOne("SnackFlowMES.Models.ApplicationUser", "InspectedBy")
                        .WithMany("QcResults")
                        .HasForeignKey("InspectedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.WorkOrder", "WorkOrder")
                        .WithMany("QcResults")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InspectedBy");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SnackFlowMES.Models.WorkOrder", b =>
                {
                    b.HasOne("SnackFlowMES.Models.BillOfMaterials", "Bom")
                        .WithMany("WorkOrders")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.ApplicationUser", "CreatedBy")
                        .WithMany("CreatedWorkOrders")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.PlanLine", "PlanLine")
                        .WithMany("WorkOrders")
                        .HasForeignKey("PlanLineId");

                    b.Navigation("Bom");

                    b.Navigation("CreatedBy");

                    b.Navigation("Item");

                    b.Navigation("PlanLine");
                });

            modelBuilder.Entity("SnackFlowMES.Models.WorkOrderCost", b =>
                {
                    b.HasOne("SnackFlowMES.Models.WorkOrder", "WorkOrder")
                        .WithOne("Cost")
                        .HasForeignKey("SnackFlowMES.Models.WorkOrderCost", "WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SnackFlowMES.Models.WorkOrderMaterial", b =>
                {
                    b.HasOne("SnackFlowMES.Models.Item", "Item")
                        .WithMany("WorkOrderMaterials")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackFlowMES.Models.WorkOrder", "WorkOrder")
                        .WithMany("Materials")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("SnackFlowMES.Models.ApplicationUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedPlans");

                    b.Navigation("CreatedWorkOrders");

                    b.Navigation("ProductionLogs");

                    b.Navigation("QcResults");
                });

            modelBuilder.Entity("SnackFlowMES.Models.BillOfMaterials", b =>
                {
                    b.Navigation("BomLines");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("SnackFlowMES.Models.Item", b =>
                {
                    b.Navigation("Bom");

                    b.Navigation("BomLines");

                    b.Navigation("InventoryBalance");

                    b.Navigation("InventoryLedgers");

                    b.Navigation("MrpRequirements");

                    b.Navigation("WorkOrderMaterials");
                });

            modelBuilder.Entity("SnackFlowMES.Models.MrpRun", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("SnackFlowMES.Models.PlanLine", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("SnackFlowMES.Models.ProductionPlan", b =>
                {
                    b.Navigation("MrpRuns");

                    b.Navigation("PlanLines");
                });

            modelBuilder.Entity("SnackFlowMES.Models.WorkOrder", b =>
                {
                    b.Navigation("Cost");

                    b.Navigation("InventoryLedgers");

                    b.Navigation("Materials");

                    b.Navigation("ProductionLogs");

                    b.Navigation("QcResults");
                });
#pragma warning restore 612, 618
        }
    }
}
